# site url
url: "https://lingt.xyz"
baseurl: "/note"

# exclude: ['_courses']

# Permalinks
permalink:           pretty

paginate:            5
excerpt_separator:   <!--more-->

title:               Ling
tagline:             'Studying at Concordia University'
description:         'A site hosting studying notes.'


# About/contact
author:
  name:              Ling
  url:               https://lingt.xyz
  email:             lingt.xyz@gmail.com

# Custom vars
version:             1.0.0

# Gems
plugins:            [jekyll-paginate]

# Use CommonMark
# markdown: CommonMark

# Add prefix to avoid ids start with numbers
kramdown:
  auto_id_prefix:   toc-
